//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqarApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> TypePaymentId { get; set; }
        public Nullable<int> FloarId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> AvailableDecrese { get; set; }
        public string Description { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string PhoneNumber1 { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string PhoneNumber4 { get; set; }
        public Nullable<int> FinishId { get; set; }
        public string videoUrl { get; set; }
    
        public virtual Finishing Finishing { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Region Region { get; set; }
        public virtual Type Type { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
